a=int(input("Enter the value for a:"))
b=int(input("Enter the value for b:"))
print("The value of a is:",a)
print("The value of b is:",b)
print("The sum of a and b is :",a+b)
print("The sub of a and b is :",a-b)
print("The Mul of a and b is :",a*b)
print("The div of a and b is :",a/b)