name=input("Enter the user name:\n")
print(f"The string is :\n {name}","\nThe length of the string is :\n",len(name))
print(name.capitalize())
print(name)
print(name.upper())
print(name.lower())
print(name.replace("rabbani","rehaan"))
print(name.split())
print(name.startswith("ra"))
print(name.endswith("rry"))
print(name.strip())
# print(name)